dependencies:
- name: demo121
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.3
- name: democheese
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: nodey27
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- alias: mydb
  name: postgresql
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 0.15.0
