dependencies:
- name: bdd-golang-http-1546937574
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-spring-1546935950
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-spring-1546936755
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: demo209
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.82
