dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: demo74
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: mynode10
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.12
- name: myvets2
  repository: http://jenkins-x-chartmuseum:8080
  version: 2.0.2
- name: cbawesome
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
