dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: demo63
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: golang-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: godemo1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: demo68
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
